openapi: 3.0.4
info:
  title: Hub log models
  description: Log models for logging services of P2P Currency Exchange Hub
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        offer:
          $ref: '#/components/schemas/HubLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    HubLogModel:
      title: Модель лога для микросервиса P2P Currency Exchange Hub
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
            - feed
            - init
            - finish
        requestOffer:
          $ref: '#/components/schemas/OfferLog'
        requestFilter:
          $ref: '#/components/schemas/OfferFilterLog'
        responseOffer:
          $ref: '#/components/schemas/OfferLog'
        responseOffers:
          type: array
          items:
            $ref: '#/components/schemas/OfferLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        code:
          type: string
        group:
          type: string
        field:
          type: string
        message:
          type: string
        level:
          type: string
        exception:
          type: string

    OfferLog:
      title: Модель лога для объявления
      type: object
      properties:
        offerId:
          type: string
        title:
          type: string
        offerType:
          type: string
        offeredCurrency:
          type: string
        desiredCurrency:
          type: string
        amount:
          type: string
        rate:
          type: string
        expectedAmount:
          type: string
        location:
          type: string
        visibility:
          type: string
        ownerId:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    OfferFilterLog:
      title: Модель лога фильтра
      properties:
        searchString:
          type: string
        ownerId:
          type: string
        dealSide:
          type: string

