openapi: 3.0.3
info:
  title: "Currency Exchange Hub ${VERSION_APP}"
  description: This is a hub where people can follow real time exchange rates and see rates from ExchangeOffer
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
tags:
  - name: ExchangeOffer
    description: Объявление о намерении обменять валюту
paths:
  /ExchangeOffer/create:
    post:
      tags:
        - ExchangeOffer
      summary: Create ExchangeOffer
      operationId: ExchangeOfferCreate
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExchangeOfferCreateRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeOfferCreateResponse'
  /ExchangeOffer/read:
    post:
      tags:
        - ExchangeOffer
      summary: Read ExchangeOffer
      operationId: ExchangeOfferRead
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExchangeOfferReadRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeOfferReadResponse'
  /ExchangeOffer/update:
    post:
      tags:
        - ExchangeOffer
      summary: Update ExchangeOffer
      operationId: ExchangeOfferUpdate
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExchangeOfferUpdateRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeOfferUpdateResponse'
  /ExchangeOffer/delete:
    post:
      tags:
        - ExchangeOffer
      summary: Delete ExchangeOffer
      operationId: ExchangeOfferDelete
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExchangeOfferDeleteRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeOfferDeleteResponse'
  /ExchangeOffer/search:
    post:
      tags:
        - ExchangeOffer
      summary: Search ExchangeOffer
      operationId: ExchangeOfferSearch
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExchangeOfferSearchRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeOfferSearchResponse'
  /ExchangeOffer/feed:
    post:
      tags:
        - ExchangeOffer
      summary: Search ExchangeOffer
      operationId: ExchangeOfferFeed
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExchangeOfferFeedRequest'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeOfferFeedResponse'

components:
  schemas:

    IRequest:
      type: object
      description: Базовый интерфейс для всех запросов
      properties:
        requestType:
          type: string
          description: Поле-дескриминатор для вычисления типа запроса
          example: create
      discriminator:
        propertyName: requestType
        mapping:
          create: '#/components/schemas/ExchangeOfferCreateRequest'
          read:   '#/components/schemas/ExchangeOfferReadRequest'
          update: '#/components/schemas/ExchangeOfferUpdateRequest'
          delete: '#/components/schemas/ExchangeOfferDeleteRequest'
          search: '#/components/schemas/ExchangeOfferSearchRequest'
          offers: '#/components/schemas/ExchangeOfferFeedRequest'

    Error:
      type: object
      properties:
        code:
          type: string
        group:
          type: string
        field:
          type: string
        message:
          type: string

    ResponseResult:
      type: string
      enum:
        - success
        - error

    IResponse:
      type: object
      description: Базовый интерфейс для всех ответов
      properties:
        responseType:
          type: string
          description: Поле-дескриминатор для вычисления типа запроса
          example: create
        result:
          $ref: '#/components/schemas/ResponseResult'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'

      discriminator:
        propertyName: responseType
        mapping:
          create: '#/components/schemas/ExchangeOfferCreateResponse'
          read:   '#/components/schemas/ExchangeOfferReadResponse'
          update: '#/components/schemas/ExchangeOfferUpdateResponse'
          delete: '#/components/schemas/ExchangeOfferDeleteResponse'
          search: '#/components/schemas/ExchangeOfferSearchResponse'
          offers: '#/components/schemas/ExchangeOfferFeedResponse'
          init: '#/components/schemas/ExchangeOfferInitResponse'

    ExchangeOfferId:
      type: string
      description: Идентификатор объявления
    ExchangeOfferTitle:
      type: string
      description: Название обьявления
    DealSide:
      type: string
      description: 'Сторона сделки: спрос или предложение'
      enum:
        - demand
        - supply
    Currency:
      type: string
      description: Название валюты
    Amount:
      type: string
      description: Сумма к обмену
    Rate:
      type: string
      description: Курс продавца
    Location:
      type: string
      description: Место совершения обмена
    UserId:
      type: string
      description: Идентификатор пользователя
    ExchangeOfferLock:
      type: string
      description: Версия оптимистичной блокировки
    ExchangeOfferVisibility:
      type: string
      description: 'Тип видимости объявления. Возможные значения: видит только владелец, только зарегистрированный в системе пользователь, видимо всем'
      enum:
        - ownerOnly
        - registeredOnly
        - public

    BaseExchangeOffer:
      type: object
      description: Объект описывает свойства, одинаковые для create и update
      properties:
        id:
          $ref: '#/components/schemas/ExchangeOfferId'
        title:
          $ref: '#/components/schemas/ExchangeOfferTitle'
        offerType:
          $ref: '#/components/schemas/DealSide'
        offeredCurrency:
          $ref: '#/components/schemas/Currency'
        desiredCurrency:
          $ref: '#/components/schemas/Currency'
        amount:
          $ref: '#/components/schemas/Amount'
        rate:
          $ref: '#/components/schemas/Rate'
        expectedAmountInDesired:
          $ref: '#/components/schemas/Amount'
        location:
          $ref: '#/components/schemas/Location'
        visibility:
          $ref: '#/components/schemas/ExchangeOfferVisibility'

    ExchangeOfferInitResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'

    ExchangeOfferCreateObject:
      allOf:
        - $ref: '#/components/schemas/BaseExchangeOffer'

    ExchangeOfferCreateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/ExchangeOfferRequestDebug'
        - type: object
          properties:
            ExchangeOffer:
              $ref: '#/components/schemas/ExchangeOfferCreateObject'

    ExchangeOfferReadObject:
      allOf:
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/ExchangeOfferId'

    ExchangeOfferReadRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/ExchangeOfferRequestDebug'
        - type: object
          properties:
            ExchangeOffer:
              $ref: '#/components/schemas/ExchangeOfferReadObject'

    ExchangeOfferUpdateObject:
      allOf:
        - $ref: '#/components/schemas/BaseExchangeOffer'
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/ExchangeOfferId'
            lock:
              $ref: '#/components/schemas/ExchangeOfferLock'

    ExchangeOfferUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/ExchangeOfferRequestDebug'
        - type: object
          properties:
            ExchangeOffer:
              $ref: '#/components/schemas/ExchangeOfferUpdateObject'

    ExchangeOfferDeleteObject:
      allOf:
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/ExchangeOfferId'
            lock:
              $ref: '#/components/schemas/ExchangeOfferLock'

    ExchangeOfferDeleteRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/ExchangeOfferRequestDebug'
        - type: object
          properties:
            ExchangeOffer:
              $ref: '#/components/schemas/ExchangeOfferDeleteObject'

    ExchangeOfferSearchFilter:
      type: object
      description: Набор фильтров для поиска
      properties:
        searchString:
          type: string
          description: Поисковая строка, которая будет искаться в объявлениях

    ExchangeOfferSearchRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/ExchangeOfferRequestDebug'
        - type: object
          properties:
            ExchangeOfferFilter:
              $ref: '#/components/schemas/ExchangeOfferSearchFilter'

    ExchangeOfferFeedObject:
      $ref: '#/components/schemas/ExchangeOfferReadObject'

    ExchangeOfferFeedRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/ExchangeOfferRequestDebug'
        - type: object
          properties:
            ExchangeOffer:
              $ref: '#/components/schemas/ExchangeOfferFeedObject'

    ExchangeOfferResponseObject:
      allOf:
        - $ref: '#/components/schemas/BaseExchangeOffer'
        - type: object
          description: Объект, который возвращается в ответе бэкенда
          properties:
            id:
              $ref: '#/components/schemas/ExchangeOfferId'
            lock:
              $ref: '#/components/schemas/ExchangeOfferLock'
            permissions:
              type: array
              uniqueItems: true
              items:
                $ref: '#/components/schemas/ExchangeOfferPermissions'

    ExchangeOfferPermissions:
      type: string
      description: Доступы для клиента для операций над объявлением
      enum:
        - read
        - update
        - delete
        - makeVisiblePublic
        - makeVisibleOwn
        - makeVisibleGroup

    ExchangeOfferResponseSingle:
      allOf:
        - type: object
          description: Ответ с одним объектом объявления
          properties:
            ExchangeOffer:
              $ref: '#/components/schemas/ExchangeOfferResponseObject'

    ExchangeOfferResponseMulti:
      allOf:
        - type: object
          description: Список найденных объектов
          properties:
            ExchangeOffer:
              type: array
              items:
                $ref: '#/components/schemas/ExchangeOfferResponseObject'

    ExchangeOfferCreateResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/ExchangeOfferResponseSingle'

    ExchangeOfferReadResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/ExchangeOfferResponseSingle'

    ExchangeOfferUpdateResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/ExchangeOfferResponseSingle'

    ExchangeOfferDeleteResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/ExchangeOfferResponseSingle'

    ExchangeOfferSearchResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/ExchangeOfferResponseMulti'

    ExchangeOfferFeedResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/ExchangeOfferResponseSingle'
        - $ref: '#/components/schemas/ExchangeOfferResponseMulti'

    # STUBS ======================
    ExchangeOfferRequestDebugMode:
      type: string
      enum:
        - prod
        - test
        - stub

    ExchangeOfferRequestDebug:
      type: object
      properties:
        debug:
          $ref: '#/components/schemas/ExchangeOfferDebug'

    ExchangeOfferDebug:
      type: object
      properties:
        mode:
          $ref: '#/components/schemas/ExchangeOfferRequestDebugMode'
        stub:
          $ref: '#/components/schemas/ExchangeOfferRequestDebugStubs'

    ExchangeOfferRequestDebugStubs:
      type: string
      description: Перечисления всех стабов
      enum:
        - success
        - notFound
        - badId
        - badTitle
        - badDescription
        - badVisibility
        - cannotDelete
        - badSearchString
